var myString;
var myNum;
var myBool;
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = "Hello " + " " + "World".slice(0, 3);
myNum = 2.2;
myBool = false;
strArr = ["Hello", "World"];
numArr = [1, 2, 3];
boolArr = [true, false, true];
strNumTuple = ['hello', 4,];
console.log(myString);
